export const BUSINESS_INFO = {
  serviceName: '차트팔자',
  serviceNameEn: 'chartpalja',
  companyName: 'onp0int',
  ceoName: '이상진',
  businessNumber: '719-24-01341',
  ecommerceNotice: '신고면제 대상',
  ecommerceNoticeDetail: '「전자상거래 등에서의 소비자보호에 관한 법률」 제12조제1항 및 「통신판매업 신고 면제 기준에 대한 고시」 제2조제1항제1호에 따른 신고면제 대상',
  ecommerceShort: '신고 면제 대상',
  address: '서울특별시 강남구 삼성로 212, 31-215',
  phone: '0502-6802-2728',
  email: 'support@onp0int.com',
  hostingProvider: 'Railway (미국)',
  privacyOfficerName: '이상진',
  privacyOfficerTitle: '대표',
  privacyOfficerEmail: 'support@onp0int.com',
  privacyOfficerPhone: '0502-6802-2728',
  serviceStartDate: '2026년 5월 1일',
  termsEffectiveDate: '2026년 5월 1일',
  privacyEffectiveDate: '2026년 5월 1일',
  refundEffectiveDate: '2026년 5월 1일',
  minAge: 14,
  ticketValidityMonths: 12,
} as const
